name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  MAVEN_COMMAND: mvn --update-snapshots --no-transfer-progress -B clean test

jobs:
  build:
    strategy:
      matrix:
        java: [ '11' ]
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
        cache: 'maven'
    - name: ulimit
      if: runner.os == 'Linux'
      run: ulimit -l
    - name: Build with ulimit
      if: runner.os == 'Linux'
      run: sudo -E bash -c "ulimit -l 65536 && ulimit -a && $MAVEN_COMMAND"
    - name: Build
      if: runner.os != 'Linux'
      run: $MAVEN_COMMAND
